// Joins the PDF extraction with the coordinate table into db/seed.sql.
// Re-run after editing db/pdf-rows.json or db/coordinates.json.
import { readFileSync, writeFileSync } from "node:fs";

const rows = JSON.parse(readFileSync(new URL("../db/pdf-rows.json", import.meta.url)));
const coords = JSON.parse(readFileSync(new URL("../db/coordinates.json", import.meta.url)));

// Geographic order of the prefecture groups, taken from the printed checklist.
const PREFECTURE_ORDER = [...new Set(rows.map((m) => m.prefecture))];

const missing = rows.filter((m) => !coords[m.fukadaNumber]);
if (missing.length) throw new Error(`no coordinates for: ${missing.map((m) => m.nameEn).join(", ")}`);

const mismatched = rows.filter((m) => coords[m.fukadaNumber].name !== m.nameEn);
if (mismatched.length) throw new Error(`coordinate/name mismatch: ${mismatched.map((m) => m.nameEn).join(", ")}`);

const q = (v) => (v === null || v === undefined || v === "" ? "null" : `'${String(v).replace(/'/g, "''")}'`);

const values = rows.map((m) => {
  const c = coords[m.fukadaNumber];
  return `  (${[
    m.fukadaNumber,
    q(m.nameKanji),
    q(m.nameKana),
    q(m.nameEn),
    q(m.prefecture),
    q(m.prefectureJa),
    PREFECTURE_ORDER.indexOf(m.prefecture) + 1,
    q(m.region),
    m.elevationM,
    q(m.bestSeason),
    q(m.notes),
    q(m.alsoIn.join(", ")),
    c.lat,
    c.lon,
  ].join(", ")})`;
});

const sql = `-- Generated by scripts/build-seed.mjs -- do not edit by hand.
-- Source: hyakumeizan-checklist.pdf (via scripts/extract-pdf.mjs) + db/coordinates.json.
-- Idempotent: re-running updates existing rows instead of duplicating them.

insert into mountains (
  fukada_number, name_kanji, name_kana, name_en, prefecture, prefecture_ja,
  prefecture_sort, region, elevation_m, best_season, notes, also_in,
  latitude, longitude
) values
${values.join(",\n")}
on conflict (fukada_number) do update set
  name_kanji      = excluded.name_kanji,
  name_kana       = excluded.name_kana,
  name_en         = excluded.name_en,
  prefecture      = excluded.prefecture,
  prefecture_ja   = excluded.prefecture_ja,
  prefecture_sort = excluded.prefecture_sort,
  region          = excluded.region,
  elevation_m     = excluded.elevation_m,
  best_season     = excluded.best_season,
  notes           = excluded.notes,
  also_in         = excluded.also_in,
  latitude        = excluded.latitude,
  longitude       = excluded.longitude;

-- Placeholder columns matching the printed checklist's A/B. Rename with
--   update people set name = 'Kriti' where name = 'A';
-- or add more from the form at the bottom of the page.
insert into people (name, sort_order) values ('A', 1), ('B', 2)
on conflict (name) do nothing;
`;

writeFileSync(new URL("../db/seed.sql", import.meta.url), sql);
console.log(`wrote db/seed.sql: ${rows.length} mountains, ${PREFECTURE_ORDER.length} prefectures`);
