// Projects a geometry source into lib/map/japan-geometry.ts.
//
// Today the source is db/coastline.json, a hand-traced placeholder. To swap in
// real geometry, convert Natural Earth (or GSI) into the same shape -- rings of
// [lat, lon] under "coastline" and "prefectures", with "source" set to
// "natural-earth" -- and re-run. Nothing downstream changes: the components,
// the peak positions and the tests are all independent of which source ran,
// because both go through lib/map/projection.mjs.
//
// Run with: npm run map:build
import { readFileSync, writeFileSync } from "node:fs";
import { project, WIDTH, HEIGHT, LAT_MIN, LAT_MAX, LON_MIN, LON_MAX } from "../lib/map/projection.mjs";

const source = JSON.parse(readFileSync(new URL("../db/coastline.json", import.meta.url)));

if (source.source !== "placeholder" && source.source !== "natural-earth") {
  throw new Error(`unknown geometry source: ${source.source}`);
}

// A point outside the extent means the projection constants and the geometry
// have drifted apart -- exactly the failure this pipeline exists to prevent, so
// fail the build rather than draw a coastline that runs off the page.
function checkInExtent(ring) {
  for (const [lat, lon] of ring.points) {
    if (lat < LAT_MIN || lat > LAT_MAX || lon < LON_MIN || lon > LON_MAX) {
      throw new Error(`${ring.name}: [${lat}, ${lon}] is outside the map extent`);
    }
  }
}

// Two decimal places on a 1000-unit map is a hundredth of a pixel at fit zoom
// and about a sixth of a pixel at the 16x maximum: far below anything visible,
// and it keeps the generated file readable.
const round = (n) => Math.round(n * 100) / 100;

function toPath(ring) {
  checkInExtent(ring);
  const steps = ring.points.map(([lat, lon], i) => {
    const { x, y } = project(lat, lon);
    return `${i === 0 ? "M" : "L"}${round(x)} ${round(y)}`;
  });
  return `${steps.join("")}Z`;
}

const coastline = (source.coastline ?? []).map(toPath);
const prefectures = (source.prefectures ?? []).map(toPath);

const file = `// Generated by scripts/build-map.mjs -- do not edit by hand.
// Source: db/coastline.json (${source.source}).
//
// Regenerate with: npm run map:build

/** Closed SVG paths in map units, from lib/map/projection.mjs. */
export const coastline: string[] = ${JSON.stringify(coastline, null, 2)};

/** Prefecture boundaries. Empty until the real geometry lands. */
export const prefectures: string[] = ${JSON.stringify(prefectures, null, 2)};

export const viewBox = "0 0 ${round(WIDTH)} ${round(HEIGHT)}";

/** Which geometry is in use, so the page can caption itself honestly. */
export const source = ${JSON.stringify(source.source)} as const;
`;

writeFileSync(new URL("../lib/map/japan-geometry.ts", import.meta.url), file);
console.log(`wrote lib/map/japan-geometry.ts: ${coastline.length} coastline rings, ${prefectures.length} prefecture rings`);
