// Projects a geometry source into lib/map/japan-geometry.ts.
//
// The source is db/coastline.json: rings of [lat, lon] under "coastline" and
// "prefectures", with "source" naming where they came from. It now holds real
// Natural Earth geometry, written by scripts/natural-earth.mjs; before that it
// was a hand-traced placeholder, and the swap moved no triangle, because both
// sources go through lib/map/projection.mjs.
//
// Two things to know before pointing it at another source:
// - This script does not simplify. Raw Natural Earth runs to thousands of
//   points for Japan, most of them finer than this map can show, so the
//   thinning belongs upstream -- see scripts/natural-earth.mjs -- not here.
// - The {name, points} contract renders each ring as exactly one filled M...Z
//   subpath, so it cannot express holes or enclaves. That is fine for a
//   coastline; if a future source needs them, the schema would need rings
//   grouped per feature plus fill-rule: evenodd.
//
// Run with: npm run map:build
import { readFileSync, writeFileSync } from "node:fs";
import { project, WIDTH, HEIGHT, LAT_MIN, LAT_MAX, LON_MIN, LON_MAX } from "../lib/map/projection.mjs";

const source = JSON.parse(readFileSync(new URL("../db/coastline.json", import.meta.url)));

if (source.source !== "placeholder" && source.source !== "natural-earth") {
  throw new Error(`unknown geometry source: ${source.source}`);
}

// A point outside the extent means the projection constants and the geometry
// have drifted apart -- exactly the failure this pipeline exists to prevent, so
// fail the build rather than draw a coastline that runs off the page.
function checkInExtent(ring) {
  // A ring with fewer than 3 points has no area. A for...of over an empty or
  // near-empty points array would pass this check trivially and toPath would
  // emit a degenerate "Z" or zero-area sliver instead of failing loudly -- the
  // most likely shape for a bad clip or simplify pass to produce once real
  // geometry is doing the converting instead of a human typing points by hand.
  if (!Array.isArray(ring.points) || ring.points.length < 3) {
    throw new Error(`${ring.name ?? "(unnamed ring)"}: a ring needs at least 3 points`);
  }
  for (const [lat, lon] of ring.points) {
    if (lat < LAT_MIN || lat > LAT_MAX || lon < LON_MIN || lon > LON_MAX) {
      throw new Error(`${ring.name ?? "(unnamed ring)"}: [${lat}, ${lon}] is outside the map extent`);
    }
  }
}

// Two decimal places on a 1000-unit map is well under a tenth of a pixel even
// at the 16x maximum, at any width this map will realistically render at: far
// below anything visible, and it keeps the generated file readable.
const round = (n) => Math.round(n * 100) / 100;

function toPath(ring) {
  checkInExtent(ring);
  const steps = ring.points.map(([lat, lon], i) => {
    const { x, y } = project(lat, lon);
    return `${i === 0 ? "M" : "L"}${round(x)} ${round(y)}`;
  });
  return `${steps.join("")}Z`;
}

const coastline = (source.coastline ?? []).map(toPath);
const prefectures = (source.prefectures ?? []).map(toPath);

const file = `// Generated by scripts/build-map.mjs -- do not edit by hand.
// Source: db/coastline.json (${source.source}).
//
// Regenerate with: npm run map:build

/** Closed SVG paths in map units, from lib/map/projection.mjs. */
export const coastline: string[] = ${JSON.stringify(coastline, null, 2)};

/** Prefecture boundaries. Still empty: Natural Earth's admin-0 countries file
    has no sub-national lines, and filling this needs its admin-1 states and
    provinces layer. The map renders whatever is here. */
export const prefectures: string[] = ${JSON.stringify(prefectures, null, 2)};

/** The whole-country frame at fit zoom. Components derive their own animated
    viewBox from the projection; this is the canonical untransformed frame. */
export const viewBox = "0 0 ${round(WIDTH)} ${round(HEIGHT)}";

/** The sources this pipeline knows how to build from. Declared as a union
    rather than inferred from the value so that a caption covering both keeps
    type-checking whichever one is currently generated. */
export type GeometrySource = "placeholder" | "natural-earth";

/** Which geometry is in use, so the page can caption itself honestly. */
export const source: GeometrySource = ${JSON.stringify(source.source)};
`;

writeFileSync(new URL("../lib/map/japan-geometry.ts", import.meta.url), file);
console.log(`wrote lib/map/japan-geometry.ts: ${coastline.length} coastline rings, ${prefectures.length} prefecture rings`);
